name: Run basic Tests

on: 
  pull_request:
    branches: [master]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/Clone project
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: echo Fernando Braga

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
